stages:
  preprocess_train:
    cmd: python src/preprocess_data.py -s 1
  preprocess_test:
    cmd: python src/preprocess_data.py -s 0 -i data/raw/1_2024-06-07_17-42.csv data/raw/2_2024-06-07_17-43.csv
  train_model:
    cmd: python src/train_model.py -m models/random_forest_v01.joblib
  test_model:
    cmd: python src/test_model.py -m models/random_forest_v01.joblib
